development: &dev
  adapter: postgresql
  encoding: unicode
  database: quor_development
  pool: 5
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  min_messages: warning

test:
  adapter: postgresql
  encoding: unicode
  database: quor_test
  pool: 5
  username: <%= ENV["USER"] %>
  password:
  allow_concurrency: true
  min_messages: error

staging:
  <<: *dev
  database: quor_development

production:
  <<: *dev
  database: quor_development

